### ISSUE TITLE
Login from the Game Pass GUI

### ISSUE THREAD

**Issue by emilsvennesson** [aqw/xbmc-gamepass#258]
It would have been cool if the login process was part of the GUI. I think a lot of new Kodi users find it confusing having to enter the username/password in the addon settings before running it. 

I know that the old Spotimc addon had this implemented:

![spotimc](https://cloud.githubusercontent.com/assets/1389407/17645251/4aba1dd0-61a0-11e6-8d1d-a2d7a0d1fd16.png)

**Comment by Displayel** [comment]
you must be kidding ?

**Comment by CraigMack69** [comment]
please close this BS.

**Comment by emilsvennesson** [comment]
@Displayel @CraigMack69: Well, if it isn't Laurel and Hardy... unless you have constructive input as to why this is not a good idea, please just refrain from posting. You're not helping at all.

**Comment by Displayel** [comment]
you will find out soon what will happen....

**Comment by BaumSchorle** [comment]
Could you guys please calm down, I am going to delete your comments since they are not related to the request at all! Could you all please stay polite and friendly!

It's a feature request, definitely a low priority one, but if someone wants to implement it, feel free!

**Comment by kaileu** [comment]
If you have problems with this Request tell us whats your Problem?
You could also make a compromise between one time login formular.
For the First time this Login Formular Appears and after this its  
saved to the settings.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
@BaumSchorle Thanks for stepping in. :-)

@emilsvennesson This was an idea we had early awhile ago, but decided it was low priority since users should only see it once (when they first enter their info).

I have noticed in a few bug reports over the years some confusion with newbies as to /where/ they should enter their account info (or whether they need any at all). Presenting the user with a login dialog when no account info is present would be a usability win IMO.

So, if you or anyone is interested on working on this, I'd be happy to review the changes and merge. :-)

---Alex

**Comment by pyrocumulus** [comment]
@aqw do you still want to keep this issue open, now that #326 has been completed?

**Comment by aqw** [comment]
@pyrocumulus Ahh, thanks for reminding me. I forgot about than.

Closing, and thanks again!

---Alex
