### ISSUE TITLE
Gamepass with phenomenal skin

### ISSUE THREAD

**Issue by ainthere** [aqw/xbmc-gamepass#273]
The text isn't showing up properly with the "phenomenal" skin.  Not that big of a deal, but thought you might want to know.

I replaced my user name with "user"
http://paste.ubuntu.com/23201876/
![kodigp](https://cloud.githubusercontent.com/assets/12841711/18626378/0987ce38-7e98-11e6-9857-6ed58d0952cd.png)

**Comment by aqw** [comment]
@ainthere This is known (#85) and is due to Kodi not having the capability to allow skinned addons (like ours) to declare their own font. So, it only works with the default font provided by Confluence. :-/

Thanks anyways for reporting, just in case. And if you know anyone who has both the capability and desire to add this feature to Kodi, you/they will receive the appreciation with the intensity of a thousand suns.

---Alex
