### ISSUE TITLE
Rewrite for the NeuLion -> Bruin/WPP

### ISSUE THREAD

**Issue by rschloeg** [aqw/xbmc-gamepass#289]
The Addon is crashing on startup, the version 0.10 on Kodi 17.3 as well as version 0.9.2 on Kodi 16.1

The logfile on Kodi 17.3 shows this error message:
Error Type: <class 'requests.exceptions.HTTPError'>
Error Contents: 404 Client Error: Not Found for url: http://gamepass.nfl.com/nflgp/servlets/simpleconsole
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 46, in <module>
 gp = pigskin(proxy_config, cookie_file=cookie_file, debug=True)
File "/storage/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 53, in __init__
  sc_data = self.make_request(url=url, method='post', payload=post_data)
File "/storage/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 452, in make_request
 req.raise_for_status()
File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 893, in raise_for_status
 raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://gamepass.nfl.com/nflgp/servlets/simpleconsole
-->End of Python script error report<--

**Comment by kaileu** [comment]
Gamepass is changing sonething on the server. The App says a new Update will comming soon.
So we have to wait till the new update.

Mit freundlichen Grüßen
Kai Leutner

**Comment by rschloeg** [comment]
Thank you very much for the quick reply. Let's hope we do not have to wait too long ...

**Comment by emilsvennesson** [comment]
I took a quick glance at the new website and it looks like they've completely thrown out Neulion, so this will likely require quite some effort to get it back running again. According to the FAQ, it will be possible to stream games in full HD (and hopefully 60 fps) so that sounds promising. :-)

**Comment by kaileu** [comment]
I found a article:
http://www.sportspromedia.com/news/nfl-agrees-new-partnerships-to-drive-game-pass-growth

So it seems you are right the partnership with neulion is gone.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@rschloeg Thanks for the bug report.

@kaileu @emilsvennesson @BaumSchorle  So... it sounds like everything is changing with GamePass. I am in the middle of a project at work that is monopolizing both my work time and my free time. By late July, I will have time to provide real help with fixing the mess GamePass has made. But until then... I won't be able to do much more than chime in and help with the occasional merge.

So, if anyone is interested in taking charge on this, I (and I imagine many others) would greatly appreciate it. Currently only I and @BaumSchorle have commit access, but if someone is willing to take charge of this, that responsibility would certainly come with full commit access --- and a case of beer from me. ;-)

And if no one is willing to take this on yet... then we'll wait until late July and see how everything is. I should have more time then.

---Alex

**Comment by aqw** [comment]
Ok, I couldn't help myself and took a quick look at the new web interface this morning. Overall, I like it, and I think it's good news. I only spent 3 or 4 minutes poking around, but they're still using .m3u8 and HLS, which is great news. Furthermore, it looks like they've ditched XML and have moved everything (?) to JSON. Hopefully this also comes with consolidating all videos into one delivery method.

They also seem to be using SVGs instead of PNGs for team logos. I don't know if Kodi supports SVGs, but if they do, that would be great for supporting multiple resolutions.

I'm going to reach out to the Plex guys and see if they'd be interested in working together on this. pigskin.py was written for the purpose of code sharing; it'd be great if we could consolidate our efforts.

The one concern I have is from the article @kaileu linked to. It specifically says that this is a partnership for Europe. I really, /really/ hope that GamePass isn't going to use one company/infrastructure for Europe and another company/infrastructure for the rest of the world. That would be horrible to support. Can anyone from... anywhere other than Europe verify that GamePass has an entire new Web UI?

---Alex

**Comment by kaileu** [comment]
@aqw no i think its global because the neulion partnership is not mentioned anymore in the english text.
In German its the old article which says the cooperate with neulion.

But the corresponding apps will be available in August. I don't know if we could use the webinterface to understand what happens.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@kaileu Cool. Hopefully it is global. :-)

As for whether we can use the web UI to understand their service... that's how this addon was originally written. Back in the day, they didn't have apps; it was only the web UI. Everything was figured out with Firebug/Devtools and a few Wireshark dumps. :-D

---Alex

**Comment by whitesnuf** [comment]
In the new FAQ the Gamepass is announced for these Countries only:

NFL Game Pass is available in the following countries:

Aland Islands, Albania, Andorra, Armenia, Austria, Azerbaijan, Belgium,Bosnia & Herzegovina, Bulgaria, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Faroe Islands, Finland, France, Georgia, Germany, Gibraltar, Greece, Guernsey, Hungary, Iceland, Ireland, Isle Of Man, Italy, Jersey, Kazakhstan, Kosovo, Kyrgyzstan, Latvia, Lichtenstein, Lituania, Luxembourg, Macedonia, Malta, Moldova, Monaco, Montenegro, Netherlands, Norway, Poland, Portugal, Romania, Russia, San Marino, Serbia, Slovakia, Slovenia, Spain, Svalbard and Jan Mayen Islands, Sweden, Switzerland, Tajikistan, Turkmenistan, Ukraine, United Kingdom, Uzbekistan, Vatican

Source: https://www.nflgamepass.com/en/faq

Bes regards, Ralf

**Comment by emilsvennesson** [comment]
I'm definitively up for helping out rewriting this. I also took a closer look and must admit that it looks promising. I wished they had moved over to MPEG-DASH rather than HLS, but it's not that big of a deal.

As for writing the code without the apps:  it's certainly possible, but personally I think it's easier and more convenient to use one of the mobile apps as base. Usually, they load/download a config on bootup with links to various parts of the API. We could do the same here. If we use the website as base, I suspect we'd have to hard code the links as well as the menu.

The bad news is that they've dropped the entire games archive except the 2016 and 2017 season. I also were not able to get anything better than 1280x720 with a 3 Mb/s bitrate, but according to the FAQ full HD should be possible so hopefully this changes in the near future.

**Comment by kaileu** [comment]
I did signup for the trial period and in the email its called NFL Gamepass Europe so maybe there will be more we will have to wait.

I have written down the Steps to watch i will attach the corresponding json files at the bottom:

Website Concept:
ClientID:
https://www.nflgamepass.com/api/en/content/v1/web/config
oauth: modules->API->REFRESH_TOKEN
season: modules->ROUTES_DATA_PROVIDERS->games
explicit week: modules->ROUTES_DATA_PROVIDERS->games_detail
GameURL: modules->DIVA->SETTINGS->type (eg: https://nflgamepass.com/api/diva/diva/settings/vod/html5)


Authentification: oauth
curl -H 'Host: www.nflgamepass.com' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' --data "client_id=42cc360e-6fbb-4472-9437-2f088b8730de&username=USERNAME&password=PASSWORD&grant_type=password" --compressed 'https://www.nflgamepass.com/api/user/oauth/token'

Season-Overview:
https://www.nflgamepass.com/api/en/content/v1/web/games/seasons
Explicit Week for gameId eg: 11158:
https://www.nflgamepass.com/api/en/content/v1/web/games/2016/post/18/list

Explicit Game and Language (en/de/etc) <videoSource format="HLS" offset="00:00:00"> <uri>akamaiuri</uri>
https://www.nflgamepass.com/api/en/content/v1/diva/11158

GameURL
curl -H 'Host: www.nflgamepass.com' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0' -H 'Accept: */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' -H 'Content-Type: application/json' --data-binary '{
	"Type": 1,
	"User": "",
	"VideoId": "11158",
	"VideoSource": "https://vod-i-video-nfl.akamaized.net/vod/4ba9bce7-d1c7-424d-aa48-40286cd38eb6/3_57160_nyg_gb_2016_h_whole_1_6000.20170526074931.ism/manifest(format=m3u8-aapl-v3,filter=hls)",
	"VideoKind": "Video",
	"AssetState": "3",
	"PlayerType": "HTML5",
	"Other": "ID|ACCESSTOKEN|web|Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20WOW64%3B%20rv%3A53.0)%20Gecko%2F20100101%20Firefox%2F53.0|undefined|USERNAME"
}' --compressed 'https://www.nflgamepass.com/api/user/api/users/v1/videoentitlement/diva/open'


Playing Game Manifest:
https://vod-i-video-nfl.akamaized.net/vod/4ba9bce7-d1c7-424d-aa48-40286cd38eb6/3_57160_nyg_gb_2016_h_whole_1_6000.20170526074931.ism/manifest(format=m3u8-aapl-v3,filter=hls)?hdnea=st=1498126034~exp=1498126049~acl=/*~hmac=f4ebff6184f3a6f0b57c9b5de1ba88a6c7ea9d21318a1acdc172df798a66f77f&hdcore=2.11.3



[NFL API.zip](https://github.com/aqw/xbmc-gamepass/files/1094444/NFL.API.zip)

**Comment by emilsvennesson** [comment]
Oh, so there's a config for the web as well: https://www.nflgamepass.com/api/en/content/v1/web/config

That's good news!

**Comment by aqw** [comment]
@whitesnuf Thanks for the info. Is there anyone here who's not from one of those countries who can confirm that they *cannot* access the new service?

@kaileu Thanks for the info.

@emilsvennesson Really happy that you're interested in helping out. I imagine the alternate bitrates will come later, or perhaps be hidden in the m3u8 files. It's early yet. Glad you found the config file as well. As I said before, there's reason for hope. At first glance, the new service looks much cleaner. :-D

---Alex

**Comment by kaileu** [comment]
I will beginn the Port to WPP if ist done i will make a Pushrequest:
https://github.com/kaileu/xbmc-gamepass/tree/wpp

There are many many Bugs in the Code ^^ and ist not playable at the Moment But for everyone who is interested.

**Comment by chovy** [comment]
What is WPP?

**Comment by kaileu** [comment]
@chovy WPP is a advertising company who bought the licence for Gamepass Europe.

**Comment by chovy** [comment]
so GamePass Europe is not on Neulion streaming platform anymore? Is WPP a streaming platform?

**Comment by aqw** [comment]
@kaileu I will cut a release with the @emilsvennesson NeuLion fix. Then, we can merge/push whatever massive breaking changes we want into master.

I took a quick look at your work, and I like the approach. Remove everything, get auth/login working, and then build it back up one feature at a time. Once you feel you've got the core of it working (and you may not be far off of that already), let's get it merged in here, and then people can pick their feature and work on it.

Also, (and I know it's too early for nitpicking the code) but when possible we should use requests rather than urllib/urllib2/urllib3 directly. It usually results in cleaner code.

---Alex

P.S. @chovy I recommend you read this thread, from the beginning. It explains everything.

**Comment by aqw** [comment]
Ok. I have merged @kaileu's PR at #292 Rather than ping-pong back and forth to get things fixed, I'm just merging it with some minor cleanup, and noting the things that need to be fixed/cleaned up.

Number one priority is:

- [ ] Restore SSL verification

According to @kaileu, thw following dopesn't work:

- [X] live games (should work; as historically they're the same as NFL Network Live)
- [ ] specific Bitrates from settings
- [ ] RedZone Archive: There is no Redzone at the moment

My list:

- [ ] Restore cookie support (assuming this is needed. before, without cookies, stream would stop playing after ~15 minutes)
- [ ] Rename "publishpoint" functions/variables, as we're no longer using publishpoint.
- [ ] Assess whether domestic support is still needed (it was removed by kaileu)
- [ ] assess/restore functionality in display_seasons_weeks()
- [ ] test ProBowl; support for adjusting their weird game info was removed
- [ ] display_shows_episodes(): thumbnails and url
- [ ] Restore coach's tape GUI (search for CoachesFilmGUI)
- [ ] cleanup bitrate stuff
- [ ] Assess how much the new service has consolidated the streams. If all streams are equal, we can consolidate a lot of logic.
- [ ] Examine imports; do we need xmltodict anymore
- [ ] Do we need to mangle the headers anymore to get all the content?
- [ ] Is gen_plid() still actually needed? Surprising to me that both services would want that oddity.
- [ ] pep8 everything (spacing, naming, cases, etc)
- [ ] all around cleanup; there's lots of fallout from these changes
- [ ] Update the readme to reflect which shows/seasons/feature/etc have been dropped by the new service.
