### ISSUE TITLE
GamePass Canada not working

### ISSUE THREAD

**Issue by colindeclue** [aqw/xbmc-gamepass#299]
I've checked the log file, and it's successfully logging me in, but still reporting "noproductaccess" despite it working for me on my computer, with the same account. Did something about the authentication change with the gamepass updates they rolled out over the summer?

[Here's](https://ares-project.uk/logupload/log.php?id=2251819) my uploaded log file.

**Comment by kaileu** [comment]
Correct me if i am wrong you are using the Version from the Kodi repo not the one from the Git Master and your are from Canada ?

**Comment by colindeclue** [comment]
Yes, I am using the version from the Kodi repo, not the one from the Git Master, and I'm in Canada.

Looking at how it logs in on the computer, it authenticates to https://gamepass.nfl.com/secure/authenticate, whereas the plugin is attempting to authenticate to https://gp.nfl.com/nflgp/secure/nfllogin.

**Comment by kaileu** [comment]
Then i have a bad News the Gamepass Version for US and for Canada isn't working at the Moment.
Gamepass splitted into 2 Version one Version for Europe and one Version for outside Europe.
Our only developers are in Europe.

If you make an undecrypted wireshark dump or a charles webproxy dump from the mobile app (apple app would be best) i can try to look if ist possible to fix the US part. If not you have to wait till there is some developer from US who wants to help.

**Comment by MHorner666** [comment]
Oh wow, this is a major bummer! I can't login, either. I am totally willing to help, but I don't know what you need me to caputre on the webproxy dump. When I launched the App from my iPhone, I saw the following relevant looking urls:

http://static.nfl.com
http://feeds.nfl.com
https://api.nfl.com

In the proxy window on the LHS, there are two tabs, Structure and Sequence. Which do you need?

In the RHS of the main proxy window, there is Overview, Contents, Summary, Chart, and Notes. I have the proxy connection on my iPhone, just tell me what to grab and I can get it.

**Comment by kaileu** [comment]
Hi,

i need the traffic from the Game Pass International App. The url should be gamepass.nfl.com or something like this. The easiest solution would be to export the whole Session. (File export Session).
Keep in mind to enable decryption of SSL and that i am able to read your password. So please change your password in something like change me log out start recording traffic with charles login and play a archive game, nfl network, a show and log out.
Stop Recording charles and change your password again.

Mit freundlichen Grüßen
Kai Leutner

**Comment by MHorner666** [comment]
Hi, Kai.

I can't find an App called "Game Pass International" in the App store for Apple (iPhone). I can find one for Android, but I thought you preferred the Apple version. 

The only way I can figure how to access Gamepass on iPhone is through the NFL Mobile App. It's integrated into it, but it doesn't look like it has its own standalone application, like on Android.

Thanks,

Matt

**Comment by kaileu** [comment]
Hmm maybe the app is delayed.
The NFL Mobile App app has another completly diffrent API :-(
The other solution would be to do this on the Website or to wait if the app will be published.

**Comment by BaumSchorle** [comment]
Hasn't GamePass in Canada been moved to a new streaming plattform DAZN!?

http://media.dazn.com/uncategorized/2017/07/dazn-launch-canada/

**Comment by aqw** [comment]
@BaumSchorle Ugh. Seriously? Game Pass is going to have /three/ different providers for 2017? This is getting to be ridiculous.

@MHorner666 Glad you're motivated to get this working. The number one thing is determining which service is providing content for Canada. Previously you mentioned neulion, which would be great, since that was the old provider and we'd (hopefully) just have to tweak stuff to get things working. So, can you do some sleuthing, and figure out of DAZN is actually handling all the streaming, or if it instead is some branding, bullshit veneer and is actually all still neulion underneath?

That'd give us a starting point. Then we can start spelunking in traffic captures. :-)

---Alex

**Comment by Ghoschdi** [comment]
I heard rumors they want to move to 1080 & 4k soon, so this could be the force behind the move?
But wonder how they want to keep people being able to travel with their GP subs and the app strategy seems to be a mess? There are still no apps for any of the new services, just checked again the windows store. Hope they will not build different apps for the regions...

I am willing to VPN & capture any data from other regions to support you if necessary.

**Comment by kaileu** [comment]
The have diffrent apps for diffrent regions.
There is  a Game Pass International App from neulion on the Android Store and an GamePass Europe App.
And you Need 2 Subscriptions if you want to use it in Europe and US etc...

**Comment by BaumSchorle** [comment]
DAZN is not only a new provider of GamePass, they have their own Apps, their own infrastructure and more.
They are called "Netflix of Sports" and they provide way more than just GamePass, they are active in Germany, Japan and now Canada and landed a big deal in Canada ;-)

So if this all is the case, I don't think we will be able to provide support for Canada in the future.

One thing we know: They hava a different app for GamePass Europe.... and a separate provider in Europe (Deltatre: http://www.deltatre.com/)

**Comment by Ghoschdi** [comment]
Okay, that breaks a lot of functionality for me, travelling the regions constantly...

Thanks for telling me that there is an android app, because have not seen it as it does not support android TV - another bad move. And thank god we have you guys building a kodi plugin, this app is in bad shape. Lost interest to tinker with it after 10 minutes...they need to improve it a lot to avoid losing some of their European customers which cannot use kodi...

**Comment by aqw** [comment]
@kaileu @BaumSchorle 

Ok, so just to make sure I have this right. If I'm wrong please correct me.

* in the Android store, there are two Game Pass apps 1) Game Pass Europe 2) Game Pass International
* Canada is likely a lost cause, as they're exclusively moving to DAZN, and the NeuLion references in colindeclue's logs are likely just part of their transition and eventually will go away.

* Game Pass Europe uses WPP/Bruin
* Game Pass International uses NeuLion

Where does the USA version of Game Pass fit into the above apps? I'd be very surprised if it's part of the "International" app.

We can take the Android apps as a signal for what services are being offered. If it's just these two, we can handle that. I just want to make sure that view is accurate before we move ahead with merging in the NeuLion support.

---Alex

**Comment by kaileu** [comment]
As far as i noticed you are right.
But i take a short peak and the Neulion Services have a completely new API....
As far as i noticed. 
I have hope for the apps that the api is diffrent there.

Mit freundlichen Grüßen
Kai Leutner

**Comment by CraigMack69** [comment]
To @BaumSchorle  point DAZN for Canadians really is a great platform. I was using the original german version for random events earlier this year. im really happy to see em spreading and even pick up the nfl deal.

**Comment by aqw** [comment]
@CraigMack69 How is this relevant? Or are you implying that they have a useful API that we can support?

---Alex

**Comment by Ghoschdi** [comment]
A quick check revealed that DAZN also has NFL rights in all other regions they serve, so bascially Season, Offseason + Redzone live  in Germany for 9,99€ / Month which covers all their sport channels. And they provide apps for basically every platform incl. native smartTV apps.
Question for me is, what are the differences, e.g. do they also offer unlimited replays and which commentary do they use? 

Side note: Amazon Prime also includes all TNF games this season.

**Comment by MHorner666** [comment]
Hi, Alex. 

I'd like to give you the view of the situation in the USA, since you're trying to gather information.

The only application I have found in Google Play or the App Store is the NFL app. That service looks like it uses neulion for some streaming. 

I do not know if the Gamepass International or Gamepass Europe apps are geo-blocked for me but I am assuming that is the case, as I live in New York and do not employ a proxy.

The bright side of this, for me, is that the NFL app is also available on the Fire Stick, which is the way I access the service to play it on my televisions. I would have preferred using the addon you guys developed for Kodi, but the NFL app now gives me the same functionality--namely, to be able to watch NFL games; although NFL Network & NFL Redzone now require an authentication from a cable provider, and Archived NFL Games (Gamepass) requires the Gamepass login.

**Comment by aqw** [comment]
@MHorner666 Thanks for the info from the US. If I'm understanding what you're saying correctly:
* there's no GamePass for the US
* the app/service has been re-branded to "NFL"
* additional sub-services are balkanized depending on cable provider, etc

If that's the case, it's unlikely this addon will support that.

---Alex
