### ISSUE TITLE
gamepass International sub - willing to help

### ISSUE THREAD

**Issue by pcrooney** [aqw/xbmc-gamepass#312]
Hi Guys, I've used your Kodi nfl gamepass plug in for years, thanks so much for your efforts. 

I understand the current challenge with gamepass international. I'm not a coder, more of a scripter/sys admin. I live in Australia and have a current subscription to gamepass. I'll help any way I can, even if I have to learn Python. Please point me in the right direction and I will do whatever it takes to help get this working.

**Comment by aqw** [comment]
@pcrooney Glad you like the addon, and are offering to help out. :-)

I have outlined the situation and required skills for supporting Game Pass International in issue #313

I too am more of a syadmin rather than a coder, so I understand where you're coming from. :-) This will require a decent amount of code and networking service spelunking. So make sure you're willing to put in that kind of effort with python learning, networking inspection, and debugging.

If so, start with issue #313, resuscitate the old functionality, and see how far that gets you. And best of luck! :-)

---Alex
