### ISSUE TITLE
Please add support for Kodi version 16

### ISSUE THREAD

**Issue by steezworld** [aqw/xbmc-gamepass#322]
First off, thank you for continuing this project! GP was so good to me last year lol I'm very grateful to be able to use it again this year thanks to you guys! Can you please make the add-on work for Jarvis though? I'd be willing to contribute in some way. Thank you for your consideration!!

**Comment by aqw** [comment]
@steezworld We have no plans to add support for a deprecated release of Kodi. With each release, Kodi tweaks the APIs, and sometimes those changes are backwards incompatible. 16->17 was one of those releases.

If you are willing to do /all/ of the effort, I have no problem keeping your changes in a publicly available branch. But IMO, the effort you'd be making would be for very little (and temporary) gain.

Personally, I recommend upgrading to Kodi 17, as it will be followed by Kodi 18 and not 16. ;-)

---Alex

**Comment by TweekDash** [comment]
@steezworld I am toying around with using gamepass on Jarvis. I may have got it to work by editing the addon.xml, I updated the xbmc.python dependency version and the xbmc.gui dependency version to the following:

```
<import addon="xbmc.python" version="2.21.0"/>
<import addon="xbmc.gui" version="5.10.0"/>

```
after I installed the other dependencies manually as noted in the readme.md section and I pasted below it seemed to install the add-on ok and looks to be running.

Requests 2.x (http://mirrors.kodi.tv/addons/jarvis/script.module.requests/)
m3u8 >= 0.2.10 (http://mirrors.kodi.tv/addons/jarvis/script.module.m3u8/)
which needs iso8601 (http://mirrors.kodi.tv/addons/jarvis/script.module.iso8601/)

I am having some problems but I don't know if those are related to my installing on jarvis or if these are general bugs. I can't play archived games at the moment but I saw someone else post that same issue. I also don't see pre-season games but I am not sure yet if that's due to what I did or a general thing. 

I'm going to install Krypton version and download the gamepass addon from the repo to see if I notice any differences with the problems I'm seeing, hope my advice/experience helps you.

**Comment by TweekDash** [comment]
update: I am pretty certain I had pulled an older copy at one point and that was the one I got working to an extent but it said "Domestic" at the top and didn't show access to the pre-season games.

I just pulled the latest gamepass version and made the same changes to the addon.xml and it installed onto Jarvis but when I went to launch the add-on I got the following error

11:55:05 T:6616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'DialogBusy'
                                            Traceback (most recent call last):
                                              File "C:\Users\name\AppData\Roaming\Kodi\addons\xbmc-gamepass-master\default.py", line 23, in <module>
                                                busydialog = xbmcgui.DialogBusy()
                                            AttributeError: 'module' object has no attribute 'DialogBusy'
                                            -->End of Python script error report<--


so I'm not sure what that means or where to go from there. 

You could maybe try the older version I had got installed to see if that would work for you. Not sure if the playing of archived games will just get fixed or require a new add-on installation, if it's going to be fixed on the back-end it could be a workaround for you. If you need me to send you that version let me know, happy to try and help

**Comment by TweekDash** [comment]
yeah i checked the changelog on the first version i installed it was "2017.06.23 v0.10.2 -- Daunte Culpepper Edition"

sorry that probably won't fix anything for you. I guess I'm going to update all my systems to Krypton unless you know how to get past the error above
