### ISSUE TITLE
Missing/Broken Shows/Incorrect Show Information

### ISSUE THREAD

**Issue by Donl5355** [aqw/xbmc-gamepass#340]
Hey guys i noticed that some shows are missing. I only have Hard Knocks, Playbook, top 100 and training camp primetime in my list for 2017.

**Comment by Donl5355** [comment]
After i edited the files like in the pull request i only have total access and gmfb episodes till august the 31

**Comment by kaileu** [comment]
Yes as i mentioned in the comment ;-)
Its because the new episodes didn't have a season value yet.
It takes some time till they tag theire episodes correctly.

A better fix needs more code changes and a bit more time to think how to do it right.

**Comment by jbarry786** [comment]
@kaileu is there a way to 'manually' add Total Access at least?

**Comment by kaileu** [comment]
Its not a problem to add this.
Its the problem how to add this ;-)

**Comment by aqw** [comment]
@Donl5355 Thanks for reporting this issue. @kaileu provided the proof-of-concept and I pushed some additional fixes.

@jbarry786 @Donl5355 Try the latest code; it should work now (with a few rough corners).

---Alex

**Comment by Donl5355** [comment]
Thanks i'll try it later.

**Comment by jbarry786** [comment]
@aqw I get an error when I try to play any of the 2018 shows:
![image](https://user-images.githubusercontent.com/30951795/30513348-a9d632f2-9af9-11e7-859c-6037582ccc76.png)

Under the 2017 tab, everything I tried worked, but Total Access only has episodes listed until August.

**Comment by kaileu** [comment]
@aqw i think you forgot to read my last Code snippet.
The whole get_shows_episodes function is broken. We can just get rid of it. Instead we already iterate through all episodes in parse_shows. These episodes should saved in an dict or an Array and in get_shows_episodes we just return the corresponding Array with Name/VideoID.

The Problem is `episodes_url = request_url.replace(':seasonSlug', season_slug).replace(':tvShowSlug', selected_show['slug'])` Returns only These episodes which has a Season in it. The "null" Season isn't listed there.
And as a guess we should use `self.get_current_season_and_week()['season']`

**Comment by aqw** [comment]
@jbarry786 The 2018 shows are a known bug/artifact from GamePass's servers. A lot of shows have the wrong broadcast date. I hope to fix that soon.

@kaileu get_shows_episodes() doesn't work for you? Everything tested out fine for me. That said, I see your point about parse_shows(), but if we do that, we need to keep that information cached (since it is so expensive to run). Perhaps we should only run it when switching between games vs the NFL Network view...

Thoughts?

I have to leave for the evening in a few minutes, so the first chance I'll have to look at this is tomorrow. But I have a bit of a full day tomorrow so it might wait until Monday. If you have a good feel for the fix, I'd say go for it, put a PR up and then I'll definitely make time to review/merge it.

---Alex

**Comment by kaileu** [comment]
I have the problem that i stuck with my idea🙈
I am doing something wrong don't know what. So my PR has to wait till i figure out how to do it right😂 (If someone can tell me how to do (my last comment on my last closed PR) i will try)

The problem with get_shows_episodes is that there aren't all avaiable episodes. Look at Total Access there are missing episodes. All episodes are only available in the Url we requested in parse_shows.
So we should use this instead the url of get_shows_epsides.

Another problem is you do twice of the internet traffic because all information you get from parse_shows and the other function is only overhead.

I would remove self.parse_shows() at the beginning of pigskin. And add it into default after klicking on nfl Network.

**Comment by aqw** [comment]
@kaileu Do you know if we merged your PR (it shows as closed, 0 commits) and/or if this is still an issue for 2018?

---Alex

**Comment by aqw** [comment]
@Donl5355 This should be fixed with the recent patches from @kaileu. All the shows show up for me. Please update to the latest code, and if you're still missing shows, please reopen this and attach a debug log.

---Alex
