### ISSUE TITLE
A football Life support

### ISSUE THREAD

**Issue by CraigMack69** [aqw/xbmc-gamepass#350]
I do not know if this has been built into the plugin yet or not, but new season started and its available via EU as i use a German IP. Props for the 1080p this year. id love to pass to something simpler and less resource hungry like FFmpeg but ill settle for your amazing addon :) great work @aqw @BaumSchorle @divingmule @eriksoderblom. what is this 3-4 seasons this addon has progressed.

**Comment by aqw** [comment]
@CraigMack69 Yeah, this is part of the overall problems in bug #340, so I'm going to close this as a duplicate.

As for something "lighter" like just straight ffmpeg... the pigskin library is kept separate in order to allow for such setups. I expect that API is going to change a lot "soon" when we integrate both Europe and International services together, but in the end, it should be a stable API that you can code a simple python script against and pipe into ffmpeg.

pigskin will be moved to its own repo once the integration happens, and an example script showing how to use it with ffmpeg is something I think would be perfect as a simple demo.

Would you mind if I ping you for your interest with that once things get moving?

---Alex

**Comment by CraigMack69** [comment]
@aqw of course you can hit me up regarding anything bud. been on this for years lol anything to help
