### ISSUE TITLE
Can't log in at all this morning. Email from NFL about changes.

### ISSUE THREAD

**Issue by aia832003** [aqw/xbmc-gamepass#365]
I can't get anything to play including archives and NFL Network Live this morning. Also got this from the NFL via email:
"The NFL Game Pass platform has been updated. You may need to log out then log in again from web and apps today in order to access the service."

**Comment by jbarry786** [comment]
I don't know if it's related with this, but unfortunately I have not been able to start any games this afternoon. :/ And checking previous weeks, no games can be played either. Looks like more people have issues so this is a general thing.

20 minutes ago it worked (I was watching the pre-game show on Kodi). Hopefully the changes will only require some tweaks in the kodi add on to get it working again.

Thanks to the developers for the continued work on this.

**Comment by Tuxglux** [comment]
Same issue her - login is working. RedZone and GameArchive are not. Everything works fine in internet browser.

**Comment by ttobsen** [comment]
Same here. To me it seems that this issue is related to the info message received from Gamepass officials. They said that a logout and re-login is needed due system update. This procedure worked fine on all my other systems (smartphone, notebook).

Is their any way to force a account logout using the Gamepass plugin? Reinstallation didn't work.

Anyway: Thanks a lot to all developers, maintenancers, supporters and so on, for this amazing plugin!

**Comment by Ghoschdi** [comment]
Works here, details: https://github.com/aqw/xbmc-gamepass/issues/363#issuecomment-336727737
________________________________
Von: Tobias Baumann<mailto:notifications@github.com>
Gesendet: ‎15.‎10.‎2017 19:55
An: aqw/xbmc-gamepass<mailto:xbmc-gamepass@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [aqw/xbmc-gamepass] Can't log in at all this morning. Email from NFL about changes. (#365)


Same here. To me it seems that this issue is related to the info message received from Gamepass officials. They said that a logout and re-login is needed due system update. This procedure worked fine on all my other systems (smartphone, notebook).

Is their any way to force a account logout using the Gamepass plugin? Reinstallation didn't work.

Anyway: Thanks a lot to all developers, maintenancers, supporters and so on, for this amazing plugin!

**Comment by OnceUponALoop** [comment]
Wrote a small python script a while back in my development environment to test changes and understand how pigskin works. 

I'm piping it through a fiddler proxy so I can better visualize the communication between pigsking and gamepass. 

I'm getting a HTTP 500 (Internal Server Error) response trying to refresh_token with an existing token. It works every 10th or 20th time. It seems their servers are still not up to snuff - what a crock, it's week 6 and they still haven't gotten their shit together.

Here's the script for reference
``` python
# -*- coding: utf-8 -*-
import json
import sys
import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__)))

import pigskin


username = 'USERNAME'
password = 'PASSWORD'

# Local Proxy to Fiddler
proxy_config = {
    'scheme': 'http',
    'host': 'localhost',
    'port': '8888',
}

# proxy_config=''

# Initialize
gp = pigskin.pigskin(proxy_config, debug=True)
try:
    gp.login(username, password)
except gp.GamePassError as error:
    print error.value

# Get this weeks stuff
this_week = gp.get_current_season_and_week()

season      = this_week['season']
season_type = this_week['season_type']
week        = this_week['week']

# Get the games for this week
weeks_games = gp.get_weeks_games(season, season_type, week)

# Set static game value to test
# Week 4 - full game - bears/packers
week = '4'
selected_gameid = '2017092800'

week = '5'
selected_gameid = '2017100500'

game_version = gp.get_game_versions(selected_gameid, '2017')

video_id = game_version['Game video']

# Get the steam
# Gametype=game for old games
# Gametype=live for live games
streams = gp.get_stream(video_id, 'game', username )

manifest_url = streams['manifest_url']

# stream_url = streams['bitrates'][6246]
```

**Comment by pyrocumulus** [comment]
@OnceUponALoop thanks for that! I was planning on doing something similar to check what is going wrong but you beat me to it. Looking at the actual requests/reponses can be quite enlightening.

@kaileu can you look at what @OnceUponALoop posted here? Because this sounds an awful lot like the problems in #363 to be honest. Could it be something like the above instead of a vague ffmpeg issue which seems to randomly affect clients? This sounds a whole lot more likely if I'm being honest.

**Comment by OnceUponALoop** [comment]
Here's my limited understanding of the changes they've been implementing over the past few weeks, i'm just guessing here so please let me know if i'm way off.

Last year and the first few weeks of this season they were just using HLS token auth (Akamai SecureHD in this case).
In week 3 it seems they enabled the Akamai SecureHD + Encryption + EdgeScape stuff which added geolocation detection and encryption on the CDN side instead of just on the content host side (gamepass). 

I assume this was done to stop people from getting an authentication token from a proxy/vpn connection and then using a direct connection to the CDN. 

It might be that the akamai edge servers now require more contact with the gamepass servers which is why the response times have been slow as hell. 

It's a feat of bad engineering to manage to slow down a CDNs response :)

**Comment by kaileu** [comment]
A Short Statement to the comment of @OnceUponALoop there is no Encryption. There is just the HDNLS Token. Last year they use a Neulion Not akamai. The only change i notice is the geolocation Check in Akamai Server itself.
I will Look tomorrow if there is Any optimisation potential.

Mit freundlichem Gruß 
Kai-Christopher Leutner

**Comment by OnceUponALoop** [comment]
@kaileu thanks for the response 👍 it clears things up a bit. I assumed encryption was added along with the EdgeScape (geolocation from akamai), i was mistaken.

What's HDNLS, tried google but got nothing - Did you mean just HLS?

**Comment by kaileu** [comment]
With this i mean the akamai sha1 hmac in the cookie line of the akamai request. Hdnea or hdnls something like that.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Displayel** [comment]
whatever happened to the addon , this was clearly another shit the bed job by the NFL yesterday...the official app was also not working again.....and all this after this mail of 20% compensation for the weeks before, its unreal they did not test this enough during the offseason.

**Comment by kaileu** [comment]
So i looked into this and the bad News i can't find any hints that the Problems are caused by anything other than ffmpeg. The oauth part is sometimes slow but that doesn't cause any issues in the end. Ffmpeg has Problems to read the first package of the files on some streams. With all streams i tested it works with inputstream. So there is nothing we can do as using inputstream or hope Kodi will integrate a new ffmpeg in the next release (which is not the case at the Moment).

**Comment by msmittag** [comment]
So that means there will be no sollution in foreseeable time?
A new Addon will not help - it needs new Kodi?

Greetings
Michael

**Comment by kaileu** [comment]
The Addon itself is working fine.
Only the ffmpeg parts of Kodi is not working.
Long Answer short: no and yes (but the current Leila branch is also not wokring)

Use inpustream for those devices where inputstream is available.
(if the Inputstream addon is disabled or not available you have to install it/activate it before using the addon)

**Comment by Ghoschdi** [comment]
Agree, it works here on Shield TV with inputstream. Only challenge I have during prime time, heavy loads on the server result in a time out and tons of errors. need to restart Kodi and try again for at least 3-4 times to get it working, but works flawlessly afterwards.

**Comment by aia832003** [comment]
@kaileu I'm not seeing the inputstream addon. Anyone point me in the right direction on installation for Shield TV. @Ghoschdi Thank!

**Comment by Ghoschdi** [comment]
Just because some people asked, here a quick how-to for inputstream: 
First of all you need to activate the Inputstream Adaptive Player manually in Kodi (as well as RTMP...) or GP will just silently deactivate the option after you enabled it there. You must activate the videoplayer addon with the following steps:

From the Kodi home screen click SYSTEM>ADD-ONS>MY ADD-ONS
Scroll down and select VIDEOPLAYER InputStream
Select the InputStream Adaptive>click Enable
Afterwards go to GP addon settings and switch to inputstream

**Comment by slh1984** [comment]
Can play it through android app but can't play Mel network or any shows also shows still missing ie timeline and a football life

**Comment by msmittag** [comment]
@Ghoschdi - tried to configure Kodi in the way you described three days ago - sorrowly still not working. Interestingly I am able to start the condensed games which is what I want in 90% of the times anyway. Would just be nice to watch a full game again any now and then...

Greetings
Michael

**Comment by darul86** [comment]
@msmittag
Look at issue 363 https://github.com/aqw/xbmc-gamepass/issues/363#issuecomment-337953634

Maybe ur inputstream Version is too old also

**Comment by slh1984** [comment]
How do you update your inputstream any help is greatly appreciated. Thanks

**Comment by ghost48** [comment]
Anbody who still has problems as I did.
I was still on Kodi 17.3 on my FireTV Gen1 and did not recognize is. A new InputStream version (from 1.0.8 to 2.0.8) comes with Kodi 17.4.

So update Kodi first to 17.4 on your device and than activate InputAdaptiveStream in Kodi and the Gamepass App as described in comment #363

**Comment by Displayel** [comment]
so i downloaded both the inputstream master and also tried the input krypton version, both failed to install on my nvidia shield with kodi 17.4 installed, Inputstream version is 2.0.10 right now.

anybody got a hint how i can update this ?

**Comment by Ghoschdi** [comment]
@Displayel: Do not fiddle with the inputstream version of Kodi, tried that before, will just cause problems. Just use the original one coming with 17.4, works flawless. 
If nothing helps, uninstall Kodi completely. Install the 17.4 from Play store, hope into Kodi 17.4 activate Inputstream like outlined in my comment above, install the latest GP addon from Kai's repo, change the GP settings to inputstream and go for it.

**Comment by Displayel** [comment]
thanks for your help, did you tried the beta of kodi 18 yet ? is the gamepass addon running on this ? have a fire tv in my bedroom, could test it on this one...the thing about the inputstream addon is it already at 2.1.4 on the peak3d github site, thought would be nice to have the latest version since i only run 2.0.10

Von meinem iPad gesendet

**Comment by Ghoschdi** [comment]
No, had no time to look into that until now. Honestly, since all my inputstream addons do what I want and lack the time, I am fine with not being at the edge (and enjoy watching GP w/o problems :) )

**Comment by Displayel** [comment]
i‘m on the road this week, couldnt try but does the FFmpeg update to 3.1.11 in kodi 17.5 solves the gamepass issue ? is it now working again with input adaptive turned off ?

**Comment by aqw** [comment]
If I'm reading this correctly, this is resolved now. If this is still a problem, feel free to reopen it.

---Alex
