### ISSUE TITLE
Hard Knocks not working

### ISSUE THREAD

**Issue by suikerchiller** [aqw/xbmc-gamepass#389]
Not sure if you're aware, but both episodes of Hard Knocks 2018 aren't working on the official / current build. Pasting the log file here as requested: http://ix.io/1kok

Will grab the latest release now and see if that solves the problem.

**Comment by suikerchiller** [comment]
Just to re-iterate on the above, problem is solved with latest release: "2018.08.15-re
lease.1.zip".

**Comment by aqw** [comment]
@suikerchiller Thanks for the bug report. The 2018.08.15 release was /just/ added to the Kodi repo, so all users should be receiving the update now-ish. Glad to hear it's resolved in the latest version. :-)

As it sounds like your problem is resolved, I will close this. If you still have problems, feel free to reopen.

---Alex
